### ISSUE TITLE
Build documentation on the fly

### ISSUE THREAD

**Issue by harikt** [auraphp/auraphp.github.com#80]
We probably need a way to build the documentation on the fly.

mwop recently wrote a [blog post](https://mwop.net/blog/2016-01-29-automating-gh-pages.html) how they are using mkdocs to send to gh-pages.

If I find sometime I will look how we can automate the same. Probably this should be done on the bin when we do a release ?

I am looking at https://github.com/auraphp/auraphp.github.com/blob/207cd64691a9a230c92b4ef73a8ee1819f1720c3/_bookdown/_packages.bookdown.json#L4-L5 and wondering how this can really get the version number when doing automation .

**Comment by martinczerwi** [comment]
Not sure if this is related, I was just browsing docs, and noticed a lot of links are pointed at the html file directly. Is this an artifact of former docs, or should both be possible.

For example when you go to the Router home page of docs [(auraphp.com/packages/3.x/Router/)](http://auraphp.com/packages/3.x/Router/), scroll down to the bottom, there's a link to /packages/3.x/Payload.html instead of /packages/3.x/Payload/. This results in a 404. 

Similarly when you start on the Router home page (docs again), the links are /packages/3.x/Router/getting-started.html, which is also a 404, instead of /packages/3.x/Router/getting-started/ which works.

**Comment by harikt** [comment]
@martinczerwi that is actually an interesting observation you have made.

Something is broken with the gh-pages . This is not related to the automatic build for all the html files are generated via [bookdown](http://bookdown.io) and is in the repo : https://github.com/auraphp/auraphp.github.com/tree/master/packages/3.x

**Comment by martinczerwi** [comment]
Ok thanks, I'll create a separate issue. I'll see if I can help.

**Comment by harikt** [comment]
@martinczerwi I have contacted the @github support . This is my understanding there is some settings in the jekyll or github to render the html contents. Some configuration needs to be added. I will also explore what the issue is.

**Comment by harikt** [comment]
Github now have a nice feature : https://github.com/blog/2228-simpler-github-pages-publishing . So if your repo have a docs folder then it can render the docs with some settings attached to it ( It needs a master branch though ) .

Experimented here : http://harikt.com/Aura.Router/

**Comment by pmjones** [comment]
Oh that's pretty neat.
