### ISSUE TITLE
Several links on docs broken

### ISSUE THREAD

**Issue by martinczerwi** [auraphp/auraphp.github.com#81]
_Copied from other issue:_ I was just browsing docs, and noticed a lot of links are pointed at the html file directly. Is this an artifact of former docs, or should both be possible?

For example when you go to the Router home page of docs (auraphp.com/packages/3.x/Router/), scroll down to the bottom, there's a link to /packages/3.x/Payload.html instead of /packages/3.x/Payload/. This results in a 404.

Similarly when you start on the Router home page (docs again), the links are /packages/3.x/Router/getting-started.html, which is also a 404, instead of /packages/3.x/Router/getting-started/ which works.

-----

This might really be related to gh-pages. I first thought you were building with Jekyll yourself, but I see now this is built into gh-pages. There was a change from Jekyll 2 to 3, that seemed similar at first (about dropping the .html suffix for links).

I need to read up on the topic, but do you think the links should be changed? Otherwise there might be a config setting related to this.

**Comment by harikt** [comment]
I found the root cause of the issue. 

The @bookdown was rendering the contents and trying to make use of jekyll layout , so all the html pages rendered then have something like https://github.com/auraphp/auraphp.github.com/blob/5abf16f98479de8ba389433b30bf96e51f89a1c3/packages/3.x/Router/getting-started.html#L1-L5 . 

From my understanding we may need to name it as `.md` and that will help to resolve the issue. But there is another issue that the old links that have `.html` will move to `folder/` structures.

@pmjones thoughts ?

**Comment by harikt** [comment]
UPDATE : That seems actually wrong for there are other `.html` files out there which do are using the same approach.

**Comment by harikt** [comment]
ok, so yes that's it. Bookdown should not use `.html` as ending to links but all is directory structure then it will render correctly.

**Comment by harikt** [comment]
> There was a change from Jekyll 2 to 3, that seemed similar at first (about dropping the .html suffix for links).

Yes we need to find a way if we can bring back the settings.

@martinczerwi sorry that I posted lots of messages regarding the issue and probably spamming your inbox.

Thank you once again for sending the report.

**Comment by harikt** [comment]
Hi @martinczerwi ,

Hope the issue has been resolved. I have made changes to have a permanent link for the bookdown generated html files. See https://github.com/auraphp/auraphp.github.com/commit/f2dc2e3b3834331932cf090ecfd6f6ff80f4d05a .

Reopen in case if you find anything broken due to the same.

Thank you

**Comment by martinczerwi** [comment]
Hi @harikt , thanks for taking care! Works fine now ;)
